### ISSUE TITLE
Acquisition Function over multiple surrogate models / outcomes

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3mbo#16]
E.g.
* expected improvement per time
* unknown constraints / probability of failure

**Comment by jakob-r** [comment]
Options

1. TimeSurrogate Class that predicts mean, se, time. Problem: not nice because not really general
2. The AcqFunction has a surrogate and a time-surrogate. Problem: Who updates the time-surrogate?
2.1 The AcqFunction$update() method - in inconsistent: Why can I update the time surrogate but not the surrogate?
2.2 The mbo loop: We would need special loops for using TEI :-1:, makes combinations (e.g. ParEGO + TEI) more complicated

More?
I like 2.1 but then I would like to update the surrogate from within the AcqFunction as well and not from the mbo loop.

**Comment by berndbischl** [comment]
1. is bad, there should be a clean surrogate which only models time

**Comment by berndbischl** [comment]
why is there ANY problem?

**Comment by jakob-r** [comment]
I think 2.1 shows that there is no problem - it just seems a bit inconsistent to update the time surrogate from within the acq_fun if we do not update the main acq_fun. But I could live with that.

**Comment by jakob-r** [comment]
4. Create a `SurrogateCollection` where each surrogate knows what it has to model

**Comment by sumny** [comment]
closed by #56
