### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by bblodfon** [mlr-org/mlr3mbo#77]
Hi! I have two questions based on the simple tuning example below:

``` r
library(mlr3verse)
#> Loading required package: mlr3
library(mlr3mbo) # needs mlr3learners, paradox and DiceKriging
#> Loading required package: mlr3tuning
#> Loading required package: paradox
set.seed(42)

lgr::get_logger('bbotk')$set_threshold('warn')

task = tsk("pima")

# 2 hyperconfigs
learner = lrn("classif.rpart",
  minsplit = to_tune(1, 100),
  cp = to_tune(lower = 1e-04, upper = 0.1, logscale = TRUE))

# TuningInstanceSingleCrit ----
instance = TuningInstanceSingleCrit$new(
  task = task,
  learner = learner,
  resampling = rsmp("holdout"),
  measure = msr("classif.ce"),
  terminator = trm("evals", n_evals = 5)
)
tuner = tnr("mbo")
tuner$optimize(instance)
#> INFO  [14:01:43.292] [mlr3] Running benchmark with 8 resampling iterations 
#> INFO  [14:01:43.381] [mlr3] Applying learner 'classif.rpart' on task 'pima' (iter 1/1) 
#> INFO  [14:01:43.417] [mlr3] Applying learner 'classif.rpart' on task 'pima' (iter 1/1) 
#> INFO  [14:01:43.437] [mlr3] Applying learner 'classif.rpart' on task 'pima' (iter 1/1) 
#> INFO  [14:01:43.563] [mlr3] Applying learner 'classif.rpart' on task 'pima' (iter 1/1) 
#> INFO  [14:01:43.585] [mlr3] Applying learner 'classif.rpart' on task 'pima' (iter 1/1) 
#> INFO  [14:01:43.604] [mlr3] Applying learner 'classif.rpart' on task 'pima' (iter 1/1) 
#> INFO  [14:01:43.624] [mlr3] Applying learner 'classif.rpart' on task 'pima' (iter 1/1) 
#> INFO  [14:01:43.646] [mlr3] Applying learner 'classif.rpart' on task 'pima' (iter 1/1) 
#> INFO  [14:01:43.669] [mlr3] Finished benchmark
#> Warning in rInfJack(pred = result$predictions, inbag = inbag.counts, used.trees
#> = 1:num.trees): Sample size <=20, no calibration performed.
#> Warning in sqrt(infjack$var.hat): NaNs produced
#>    minsplit       cp learner_param_vals  x_domain classif.ce
#> 1:       92 -4.20205          <list[3]> <list[2]>   0.233877

instance$archive
#> <ArchiveTuning>
#>    minsplit   cp classif.ce runtime_learners              timestamp batch_nr
#> 1:       92 -4.2       0.24            0.014 2022-08-08 14:01:43.78        1
#> 2:       41 -9.1       0.26            0.009 2022-08-08 14:01:43.78        1
#> 3:       43 -2.9       0.26            0.113 2022-08-08 14:01:43.78        1
#> 4:       54 -3.0       0.22            0.010 2022-08-08 14:01:43.78        1
#> 5:       42 -4.0       0.23            0.009 2022-08-08 14:01:43.78        1
#> 6:       10 -2.6       0.26            0.010 2022-08-08 14:01:43.78        1
#> 7:       39 -4.9       0.23            0.012 2022-08-08 14:01:43.78        1
#> 8:       20 -4.7       0.25            0.011 2022-08-08 14:01:43.78        1
#>    warnings errors      resample_result
#> 1:        0      0 <ResampleResult[21]>
#> 2:        0      0 <ResampleResult[21]>
#> 3:        0      0 <ResampleResult[21]>
#> 4:        0      0 <ResampleResult[21]>
#> 5:        0      0 <ResampleResult[21]>
#> 6:        0      0 <ResampleResult[21]>
#> 7:        0      0 <ResampleResult[21]>
#> 8:        0      0 <ResampleResult[21]>
```

<sup>Created on 2022-08-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

1) Why it BO always does 8 resamplings in the beggining? (a bug or a feature? :)
2) Are the `NaNs produced` worrying or kinda expected (due to low `n_evals`)? I see that when I increase the number of evaluations (`n_evals`), the warnings do not appear anymore.

**Comment by sumny** [comment]
Hi @bblodfon and thanks for your interest in `mlr3mbo`.

1. Why it BO always does 8 resamplings in the beggining? (a bug or a feature? :)

Recall that BO is an iterative procedure that relies on a (probabilistic) surrogate model whose mean and variance prediction are used in an acquisition function to determine the next candidate point for evaluation.

To be able to fit a surrogate (e.g., a Gaussian process or something else like a random forest), we need some initial evaluations of hyperparameter configurations and their performance. These evaluations are called the initial design.
In `mlr3mbo` we currently use a default of `4D` points as the initial design (where `D` is the dimensionality of your search space, e.g., in your example `2` due to `minsplit` and `cp`).

If you do want to change this, then you can currently do this, by passing the following to the `args` active binding of the `Tuner`:
`tuner$args = list(init_design_size = 10)` would result in using a fixed initial design size of `10`.
To see all other passable `args` if you use the `bayesopt_ego` loop function (the default when doing single-objective HPO like in your example) see the documentation of `?bayesopt_ego` (note that `instance`, `surrogate`, `acq_function`, and `acq_optimizer` cannot be passed as args but have their own active bindings directly, see `?TunerMbo`).
Note that this API may not be final (and we are currently in the progress of finalizing some design decisions and getting `mlr3mbo` to CRAN), so this may change in the future but if it does then it will be well documented.

Finally, note that if you terminate by `evals` (`terminator = trm("evals", n_evals = 5)`) then you should always use more `n_evals` then the initial design (otherwise the tuning result is only based on the initial design evaluated so far).
For 2 numeric hyperparameters, a somewhat reasonable `n_evals` could be around `20` to `50` but this depends on the problem at hand (and also the initial design size). We may, in the future, provide more sophisticated terminators for BO (that can terminate on their own).

2. Are the NaNs produced worrying or kinda expected (due to low n_evals)? I see that when I increase the number of evaluations (n_evals), the warnings do not appear anymore.

First, I noticed that the `Tuner` implicitly uses a random forest as a surrogate in your example. If you update `mlr3mbo` to the most recent version, it should use a Gaussian process (I believe).

Nevertheless,
```
#> Warning in rInfJack(pred = result$predictions, inbag = inbag.counts, used.trees
#> = 1:num.trees): Sample size <=20, no calibration performed.
#> Warning in sqrt(infjack$var.hat): NaNs produced
```
tells you that no calibration was performed when the variance prediction of the random forest was obtained via the `infjack` method (`?predict.ranger`). This calibration is only performed if more than `20` data points are available and the initial design size was 8 (default).
After having evaluated 20 configurations, the random forest will no longer complain during the prediction step.
So all in all, the warning should not be that worrying (the random forest will still be able to make predictions and you should see this when you inspect the `instance$archive$data`: the column of the acquisition function - in your case `acq_ei` due to using expected improvement as default - is only NA for the initial design and not afterwards).
You could also get rid of the warning by using an initial design size `>= 20` or using a different prediction method for the ranger or a different surrogate (e.g., a Gaussian process).

Feel free to ask if you have any other questions and close the issue if you found my answers helpful :)

**Comment by bblodfon** [comment]
Hi @sumny,

Thanks for the taking the time to write so elaborate answers as well as pointers to the appropriate documentation! I only have a vague understanding of how these things work, and in general BO seemed like a really cool tuning strategy to try for my `mlr3` models. But good answers generate more questions :) so here are 2 more:

1. You mentioned that I use a random forest as a surrogate based on the warnings, but is there any way to properly check which one I am using in the code?

    => I ran `tuner$acq_function$surrogate$model` after the optimization was done and got a `LearnerRegrKM:regr.km` type model, does that tell you anything?

    And if it's not a GP, how can I change the surrogate to be one? I am using the latest version `0.0.0.9000` of the package.

2. Having the GP as the default is based on research or practice? i.e. is there any general guidelines for which one to use in different scenarios (e.g. different datasets, learners, etc)?

**Comment by sumny** [comment]
@bblodfon 

Nice follow-up questions!

1. Indeed, to check which surrogate the tuner used, simply check the `tuner$surrogate$model` field (or `tuner$acq_function$surrogate$model`; they both point to the surrogate). If you did not pass a surrogate during construction (`tuner = tnr("mbo")`), a default surrogate will be constructed on the fly and the field will therefore only contain the surrogate after the optimization terminates (or errors). As a tip, you can use `default_surrogate(instance)` to see what default surrogate `mlr3mbo` will use (depending on your instance and the search space); note that there are also other `default_*` functions (acqfun, acopt, loopfun).

If you call `default_surrogate(instance)` in your example, you will see that `mlr3mbo` wants to use a GP (`regr.km` is a GP, i.e., a kriging model) as a default:
```
surrogate = default_surrogate(instance)
surrogate$model
```

However, `mlr3mbo` has plenty of try catch and fallback mechanisms in the case of something going wrong during training the surrogate or predicting with the surrogate.

```
surrogate$model$fallback
```

tells you that the surrogate uses a random forest (`regr.ranger`) as a fallback if the GP fails to train.

You may also always want to inspect `tuner$surrogate$model$errors` (and also `$warnings`) after the optimization to see if something went wrong with the surrogate and if the fallback got triggered (note, that this also depends on how `surrogate$model$encapsulate` was set, see `?Learner` and the section about `encapsulate` and `?mlr3misc::encapsulate`).

In the very worst case (surrogate and its fallback fail), `mlr3mbo` will propose a point sampled uniformly at random for the next evaluation. You can see whether this happened, if the acquisition function column in `instance$archive$data` contains NA values beyond the initial design.

So to get back to your case, `mlr3mbo` tried to use a GP but could not due to both `DiceKriging` and `rgenoud` being needed (providing a subroutine for the fitting of the GP as configured by `mlr3mbo`) and therefore used a random forest as a fallback (and while predicting with the random forest, the warning above was triggered). I also opened an issue about this (#78) and will try to provide some related quality of life fixes.

2. A GP should work well with low-dimensional (purely numeric) search spaces (no mixed and/or hierarchical search spaces, otherwise you need fancy kernels that are not implemented in `DiceKriging`). However, in practice, fitting the GP can still be difficult. Usually one would transform the x and y space to the unit cube prior to fitting and re-transform during prediction to be able to specify tight priors on the length scale hyperparameters of the GP (but `mlr3mbo` currently does not do this as this also was not done in the "old" `mlrMBO`; However, I may change the default GP used by `mlr3mbo` in the near future to use such scaling techniques). Characteristics of the dataset are not important as the surrogate is fitted on (hyperparameter, performance) values. So the recommendation would be to use a GP for low-dimensional numeric search spaces (but make sure to check that no callbacks / try catch mechanism was triggered). As an alternative, a random forest (popularly used by SMAC) is quite robust (although it is not a probabilistic model and does not have a "real" posterior distribution like the GP - which has its downsides, at least theoretically for the BO setting. Still a random forest often works very well in practice.

**Comment by bblodfon** [comment]
Thank again for a very thorough explanation and advice! Also glad that you created the issue to make it easier for future users to install the dependencies required. Good work and software - hope it gets published somewhere with lots of info on its capabilities!

BR, John.
